setting:
  seed: 20000812
  ROOTDIR: './'
  os_environ:
    WANDB_API_KEY: ~
    WANDB_RUN_ID: ~
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    MASTER_ADDR: localhost
    MASTER_PORT: 12315
    WORLD_SIZE: 1
    NODE_RANK: 0
  wandb_config:
    project: Thermostability
    name: esm2_t33_650M_UR50D
  tensorboard_config:
    save_dir: "./tensorboard/"
    name: Thermostability
    version: Thermostability
    log_graph: False
    default_hp_metric: True
    prefix: ""

model_checkpoint:
  monitor: "valid/valid_loss" # name of the logged metric which determines when model is improving
  mode: "min" # "max" means higher metric value is better, can be also "min"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  verbose: True
  dirpath: ""
  filename: "valid_loss_{valid/valid_loss:.5f}"
  auto_insert_metric_name: False
  save_weights_only: True

model:
#    Which model to use
  model_py_path: dplm/dplm_regression_model
  kwargs:
#    Arguments to initialize the specific class
    net_name: airkingbd/dplm_650m
    load_pretrained: True
    load_prev_scheduler: True
    save_top_k: 1

    freeze_backbone: 0
    dropout: 0.0
    use_lora: 0


#    Arguments to initialize the basic class AbstractModel
  lr_scheduler_kwargs:
    last_epoch: -1
    init_lr: 2.0e-5
#    Weather to use this scheduler or not
    on_use: false

  optimizer_kwargs:
    betas: [0.9, 0.98]
    weight_decay: 0.01

  save_path: checkpoints/Thermostability_dplm_650m


dataset:
#    Arguments to initialize the basic class LMDBDataset
  dataset_py_path: dplm/dplm_regression_dataset
  dataloader_kwargs:
    batch_size: 2
    num_workers: 8

  train_lmdb: LMDB/Thermostability/normal/train
  valid_lmdb: LMDB/Thermostability/normal/valid
  test_lmdb: LMDB/Thermostability/normal/test
#    Arguments to initialize the specific class
  kwargs:
    tokenizer: airkingbd/dplm_650m
    mix_max_norm: [40, 67]


#  Arguments to initialize Pytorch Lightning Trainer
Trainer:
  max_epochs: 200
  log_every_n_steps: 1
  strategy:
    find_unused_parameters: True
  logger: false
  # enable_checkpointing: false
  val_check_interval: 1.0
  accelerator: gpu
  devices: 8
  num_nodes: 1
  accumulate_grad_batches: 1
  precision: 16
  num_sanity_val_steps: 0
  enable_progress_bar: true


