_target_: uniref50

# data_dir: ${data_dir} # data_dir is specified in config.yaml
data_dir: ${paths.data_dir}/uniref50
# dataloader related
max_tokens: 6000
max_len: 1022
sort: false
num_workers: 8
pin_memory: true

mini_run: false